### ISSUE TITLE
Métodos de coleta de dados 

### ISSUE THREAD

**Issue by adrienesantana01** [ArthurViniciusE/pep2_n0xus#15]
Observar quais os métodos de coleta de dados do usuário serão utilizados.

**Comment by adrienesantana01** [comment]
As técnicas usadas pela equipe para coletar dados do cliente foram:

1. Entrevista;
2. Investigação contextual;
3. Estudo de caso.

**Comment by adrienesantana01** [comment]
Fomos no local de trabalho da cliente, mostramos o protótipo e fizemos a entrevista, coletando dados para entender melhor como iremos criar o sistema.

**Comment by adrienesantana01** [comment]
Também observamos a rotina da cliente e participamos um pouco da sua aula, durante a aula conseguimos analisar vários pontos em que poderemos ajudá-la com o nosso sistema.

**Comment by ranierivalenca** [comment]
Colocar dados não sensíveis aqui

**Comment by adrienesantana01** [comment]
Editei os comentários especificando os dados que recolhemos durante a visita ao stúdio.

**Comment by adrienesantana01** [comment]
Foi criado uma nova issue com os os dados que recolhemos.
