### ISSUE TITLE
Estudar migration de banco no laravel, e tentar migrar o banco do projeto.

### ISSUE THREAD

**Issue by ArthurViniciusE** [ArthurViniciusE/pep2_n0xus#17]

**Comment by adrienesantana01** [comment]
Referencia de como fazer uma migration
link :  https://magazine.softerize.com.br/tutoriais/php/laravel/banco-de-dados-laravel

**Comment by adrienesantana01** [comment]
As técnicas de coletas de dados que iremos usar com o cliente será:
1. - Entrevista;
2. - Investigação Contextual;
3. - Estudo de caso.

**Comment by ranierivalenca** [comment]
Vocês já tem o modelo de dados? Alguma modelagem lógica que possa ser colocada aqui (ou em alguma issue relacionada)?

**Comment by adrienesantana01** [comment]
Fizemos uma issue na sprint anterior e já temos o modelo físico na branch de Guilherme Gomes.
