### ISSUE TITLE
Estudar Vue.js

### ISSUE THREAD

**Issue by ArthurViniciusE** [ArthurViniciusE/pep2_n0xus#18]

**Comment by ranierivalenca** [comment]
Alguma referência de Vue pra gente estudar? =)

**Comment by ArthurViniciusE** [comment]
Foi mal chefe, deixei favoritado no navegador e esqueci de por aqui.

**Comment by ArthurViniciusE** [comment]
Uma introdução:
https://www.schoolofnet.com/curso/frontend/vuejs/iniciando-com-vuejs-2-rev3/

https://www.udemy.com/introducao-ao-vue-js-2/?ranMID=39197&ranEAID=0cH85k*Fpl0&ranSiteID=0cH85k.Fpl0-V98mVuwmaPeLkOvmftZWHA&LSNPUBID=0cH85k*Fpl0
