### ISSUE TITLE
Definir detalhadamente o projeto

### ISSUE THREAD

**Issue by adrienesantana01** [ArthurViniciusE/pep2_n0xus#2]

**Comment by luizcsrj** [comment]
Clínica de Pilates:
-Sistema de login para unica administradora;
-Turmas separadas por dias (segundas e quartas/terças e quintas) definidas em horários determinados pela administradora;
-A administradora pode adicionar turmas no dia em que ela especificar;
-A administradora poderá adicionar alunos nas turmas;
-O adicionar alunos terá todos os dados do novo aluno que entrará na turma especificada;
-As turmas terão exercícios semanais;

obs:
-Os exercícios serão adicionados brevemente após uma reunião com a cliente.
-atualizações e modificações serão feitas ao decorrer do projeto;
