### ISSUE TITLE
Reunião para organização do projeto

### ISSUE THREAD

**Issue by ArthurViniciusE** [ArthurViniciusE/pep2_n0xus#24]
Eu como Scrum master quero que o git hub esteja organizado para que commites duplicados sejam retirados.

**Comment by adrienesantana01** [comment]
Fizemos e reunião e criamos as issues para a sprint da semana.

**Comment by adrienesantana01** [comment]
Por causa da paralisação do dia 15/05 pensamos na possibilidade de remarcar a visita com a cliente

**Comment by adrienesantana01** [comment]
Remarcamos a visita para o dia 22/05 às 9:30hrs da manhã.
