### ISSUE TITLE
Segunda mostra do projeto para o cliente.

### ISSUE THREAD

**Issue by GuilhermeEvaristo** [ArthurViniciusE/pep2_n0xus#29]
Como analista, quero marcar um dia para mostrar o andamento do projeto e receber um possível feedback do cliente.

**Comment by adrienesantana01** [comment]
Entrei em contato com a cliente e estou tentando marcar a data e a hora da visita.

**Comment by adrienesantana01** [comment]
A visita está marcada para o  dia 15/05 as 15:30 horas
